# Generated by Django 2.2.6 on 2019-10-30 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmat_questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(blank=True, null=True)),
                ('correct', models.BooleanField(blank=True, null=True)),
                ('time_spent', models.FloatField(blank=True, null=True)),
                ('choice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_choice', to='gmat_questions.Questions')),
            ],
        ),
    ]
