# Generated by Django 2.2.6 on 2019-10-31 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmat_questions', '0004_auto_20191031_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswers',
            name='choice_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_choice', to='gmat_questions.Questions'),
        ),
    ]
